name: Update Database File Name

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天早上8点运行

jobs:
  rename:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y rename

      - name: Rename database file
        run: |
          DATE_TODAY=$(date +"%m-%d")
          FILE_YESTERDAY="数据库${DATE_YESTERDAY}.kdbx"
          FILE_TODAY="数据库${DATE_TODAY}.kdbx"
          rename "s/数据库*.*\.kdbx/$FILE_TODAY/" *.kdbx

      - name: Commit and push if it changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if [[ $(git diff --stat --staged) != '' ]]; then
            git commit -m "Renamed database file"
            git push
          fi
